name: Deploy Vite dist to deploy branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./old-woodman-front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Deploy dist to deploy branch
        working-directory: ./ # ⚠️ ВАЖНО: выйти обратно в корень проекта
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ ! -d old-woodman-front/dist ]; then
            echo "❌ dist не найдена. Сборка не сработала"
            exit 1
          fi

          mkdir deploy-tmp
          cp -R old-woodman-front/dist/* deploy-tmp/

          git checkout --orphan deploy
          git rm -rf . > /dev/null || true
          cp -R deploy-tmp/* .
          rm -rf deploy-tmp

          git add .
          git commit -m "Deploy production build"
          git push -f origin deploy
