name: Deploy Vite dist to deploy branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: old-woodman-front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Deploy dist to deploy branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          mkdir ../deploy-tmp
          cp -R dist/* ../deploy-tmp/
          
          cd ..
          git checkout --orphan deploy
          rm -rf *
          cp -R deploy-tmp/* .
          rm -rf deploy-tmp
          
          git add .
          git commit -m "Deploy production build"
          git push -f origin deploy
